export const projectsArray = [
  {
    image: '/Image/Portfolio.png',
    title: 'Portfolio',
    technologies: [
      'React',
      'NextJS',
      'Tailwind CSS',
      'JavaScript',
      'HTML',
      'CSS',
    ],
    description: [
      'This is a personal portfolio that I made to show my skills and experiences.',
    ],
    link: 'https://github.com/Crautor/Portfolio',
    where: 'GitHub',
  },
  {
    image: '/Image/Feeder.png',
    title: 'Fry Feeder',
    technologies: [
      'Arduino',
      'C++',
      'Electronics',
      'Sensors',
      'IoT',
      'Resistors',
    ],
    description: ['Fry feeder project made for the fish-in os project.'],
    link: 'https://github.com/Crautor/FISH-INOS/tree/main/Alimentador',
    where: 'GitHub',
  },
  {
    image: '/Image/CPA.png',
    title: 'CPA Website',
    technologies: [
      'HTML',
      'CSS',
      'JavaScript',
      'Bootstrap',
      'Sanity',
      'API',
      'Figma',
    ],
    description: [
      'Website project made for the CPA of the biopark education college.',
    ],
    link: 'https://github.com/Crautor/CPA-2.0',
    where: 'GitHub',
  },
  {
    image: '/Image/InventoryManagement.png',
    title: 'Inventory management',
    technologies: [
      'Java',
      'Spring Boot',
      'CSS',
      'JavaScript',
      'ThymeLeaf',
      'MySQL',
      'API',
      'Figma',
    ],
    description: [
      'Website project made to controlling equipment and utensils used in Biopark Educação.',
    ],
    link: 'https://gitlab.com/grupo01ads3/controledeestoque',
    where: 'GitLab',
  },
];
